### ISSUE TITLE
rna sample number dupicates

### ISSUE THREAD

**Issue by HollyLeanneBrown** [BrentLab/database_files#3]
the example is in s1CDNASample_hbrown_10.29.19

so this has samples that failed in the original run and I put them into a new library prep. They do have different rnaDate values. Since one of the key columns is different will this be ok?

**Comment by cmatKhan** [comment]
Key columns absolutely must correspond exactly to one another. 

For each sheet, there is a set of three columns which uniquely identify a given sample forward, and a set of three columns which do the same back to the previous sheet (with the exception of bioSample, which only has three keys pointing forward as it is the first, and fastqFiles which only has three key columns connecting back, because it is the last).

**Comment by cmatKhan** [comment]
Also -- the specs currently say that all replicate columns are integer values. I haven't checked this afternoon, but as of this morning, there are still values like the following:

"1 a"

in replicate columns. Two issues:

 1) There should be no spaces in any of the column entries
 2) That's not an integer value

the replicate specifications probably need to be updated. Two options:

decimal values, eg a technical replicate could be 1.1 if it is a technical replicate of a replicate named 1. However, this may get too confusing.

Another option would be "1a", etc. But, I'm not sure if that will be descriptive enough, either -- probably you and Jessica should talk about this and figure out what is both most descriptive, and easiest.

Most important thing right now is that a specification is chosen, and adhered to -- variation in this will make it hard to figure out what corresponds to what

**Comment by cmatKhan** [comment]
Yes -- the key is the set of columns (date, preparer, sampleNumber) -- those three together combined need to be unique, not one individually
